spring:
  mvc:
    servlet:
      path: /api
datasource:
  url: jdbc:mysql://host.docker.internal:3307/chatApp
  username: root
  password: YOURNEWPASSWORD
  driver-class-name: com.mysql.cj.jdbc.Driver

