spring:
  application:
    name=documentManagement
  h2:
    console.enabled=true
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/chatApp
    username: root
    password: YOURNEWPASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.pad.api.configuration.CustomTableNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    liquibase:
      change-log=classpath:db/changelog/db.changelog-master.xml

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    url: /v3/api-docs

logging:
  file:
    name: logs/application.log
  level:
    root: INFO
    org.pad.api: DEBUG

jwt:
  secret: ZGhpZ3NzcGxsaXJlY2t0ZGhsaWJmZGgzbHJsZGZpbGVyaG5zcGhsZGZzZGQ=
