version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: chatApp_db
    environment:
      MYSQL_ROOT_PASSWORD: YOURNEWPASSWORD
      MYSQL_DATABASE: chatApp
    ports:
      - "3307:3306"
    networks:
      - back-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev.production
    depends_on:
      db:
        condition: service_healthy

networks:
  back-net:
    driver: bridge
